const test=require('node:test');
const assert=require('node:assert/strict');
const {createRuntime}=require('../scripts/page-runtime.cjs');
function setup(){const r=createRuntime();r.run(`const candidate={code:'600001',name:'测试',catalystScore:19.44,premarketScore:46.38,limitScore:0};const quote={code:'600001',name:'测试',auction:2.5,currentChange:2.5,amount:100000};const pool={sourceCoverage:{previousLimitPool:false}}`);return r}
test('missing limit coverage is not treated as confirmed zero performance',()=>{const r=setup();const unknown=r.run('evaluatePremarketCandidate(candidate,quote,pool)');const known=r.run('evaluatePremarketCandidate(candidate,quote,{sourceCoverage:{previousLimitPool:true}})');assert.ok(unknown.finalEventScore>known.finalEventScore);assert.ok(unknown.missingFactors.some(x=>x.includes('涨停池')));assert.equal(unknown.amountScore,null);assert.ok(unknown.finalEventScore>=60)});
test('amount only scores with explicit comparable auction baseline',()=>{const r=setup();assert.equal(r.run('evaluatePremarketCandidate(candidate,{...quote,auctionAmountBaseline:100000},pool).amountScore'),null);assert.equal(r.run("evaluatePremarketCandidate(candidate,{...quote,amountBasis:'auction',auctionAmountBaseline:100000},pool).amountScore"),50)});
test('missing quotes, ST and procedural announcements cannot qualify',()=>{const r=setup();for(const expression of ['candidate,undefined,pool',"{...candidate,name:'*ST测试'},quote,pool","{...candidate,events:[{eventType:'定期报告',eventTitle:'年报更正'}]},quote,pool"]){assert.ok(r.run('evaluatePremarketCandidate('+expression+').rejectionReasons.length')>0)}});
test('diagnostics distinguish missing input and candidates rejected by score',async()=>{const r=setup();await r.run("preparePremarketObservation([quote],{...pool,candidates:[candidate,{...candidate,code:'600002'}]})");assert.equal(r.run('premarketPick.code'),'600001');assert.match(r.elements.get('premarketPick').innerHTML,/当日报价缺失/);assert.match(r.elements.get('premarketPick').innerHTML,/候选评分明细/)});
test('a weak catalyst still fails and results do not depend on pool size',()=>{const r=setup();assert.ok(r.run('evaluatePremarketCandidate({...candidate,catalystScore:5},quote,pool).finalEventScore')<60);assert.equal(r.run('evaluatePremarketCandidate(candidate,quote,pool).finalEventScore'),r.run('evaluatePremarketCandidate(candidate,{...quote,amount:999999999},pool).finalEventScore'))});
